USE herois;

INSERT INTO super_heroi (id, nome, apelido, superPoder, fraqueza, historiaOrigem, primeiraAparicao) VALUES
(1, 'Clark Kent', 'Superman', 'Super força, voo, visão de calor', 'Kryptonita', 'Nascido no planeta Krypton e enviado à Terra como um bebê.', '1938-06-01'),
(2, 'Bruce Wayne', 'Batman', 'Habilidades de combate, inteligência, gadgets avançados', 'Falta de poderes super-humanos', 'Após testemunhar o assassinato de seus pais, jurou proteger Gotham City.', '1939-05-01'),
(3, 'Diana Prince', 'Mulher-Maravilha', 'Força divina, agilidade, Laço da Verdade', 'Laços emocionais', 'Princesa das Amazonas, treinada como guerreira desde criança.', '1941-12-01'),
(4, 'Peter Parker', 'Homem-Aranha', 'Força sobre-humana, escalada de paredes, sentido aranha', 'Responsabilidade pessoal', 'Após ser mordido por uma aranha radioativa, adquiriu habilidades especiais.', '1962-08-01'),
(5, 'Tony Stark', 'Homem de Ferro', 'Inteligência, traje de combate avançado', 'Dependência do traje', 'Bilionário industrial que criou uma armadura para salvar sua vida e proteger o mundo.', '1963-03-01'),
(6, 'Barry Allen', 'Flash', 'Velocidade extrema, viagem no tempo', 'Força da Velocidade pode ser instável', 'Adquiriu velocidade sobre-humana após ser atingido por um raio durante um experimento.', '1956-10-01'),
(7, 'Steve Rogers', 'Capitão América', 'Força e agilidade aprimoradas', 'Incompatibilidade com o mundo moderno', 'Transformado em um super soldado durante a Segunda Guerra Mundial.', '1941-03-01'),
(8, 'Arthur Curry', 'Aquaman', 'Força sobre-humana, comunicação com criaturas marinhas', 'Desidratação em longos períodos fora da água', 'Rei de Atlantis, com habilidades especiais relacionadas ao mar.', '1941-11-01'),
(9, 'Natasha Romanoff', 'Viúva Negra', 'Habilidades de espionagem e combate', 'Laços emocionais', 'Agente altamente treinada da S.H.I.E.L.D., com um passado sombrio.', '1964-04-01'),
(10, 'Hal Jordan', 'Lanterna Verde', 'Poder do anel, projeção de energia', 'Limitações do poder do anel', 'Escolhido pelo anel dos Lanternas Verdes, Hal protege o universo.', '1959-07-01'),
(11, 'Ororo Munroe', 'Tempestade', 'Controle climático, voo', 'Claustrofobia', 'Nasceu com a habilidade de controlar o clima e foi adorada como uma deusa na África.', '1975-05-01'),
(12, 'Logan', 'Wolverine', 'Fator de cura, garras de adamantium', 'Perda de memória', 'Mutante com habilidades regenerativas e garras retráteis cobertas de adamantium.', '1974-11-01'),
(13, 'Matt Murdock', 'Demolidor', 'Sentidos aguçados, habilidades de combate', 'Cegueira', 'Após um acidente com produtos químicos, ficou cego, mas seus outros sentidos foram ampliados.', '1964-04-01'),
(14, 'Victor Stone', 'Cyborg', 'Força sobre-humana, tecnologia avançada', 'Dependência de sistemas cibernéticos', 'Transformado em um ser meio humano, meio máquina após um acidente devastador.', '1980-10-01'),
(15, 'Jean Grey', 'Fênix', 'Telepatia, telecinese', 'Incapacidade de controlar os poderes', 'Mutante com poderes telepáticos e telecinéticos, foi possuída pela entidade Fênix.', '1963-09-01'),
(16, 'T\'Challa', 'Pantera Negra', 'Força, agilidade, inteligência sobre-humana', 'Responsabilidades reais', 'Rei de Wakanda e defensor da nação como o Pantera Negra.', '1966-07-01'),
(17, 'Shazam', 'Shazam', 'Força e velocidade sobre-humanas, manipulação de raios', 'Imaturidade', 'Quando Billy Batson pronuncia a palavra "Shazam", transforma-se em um herói adulto.', '1940-02-01'),
(18, 'Betsy Braddock', 'Psylocke', 'Telepatia, habilidades psíquicas', 'Fragilidade emocional', 'Originalmente uma modelo britânica, teve seu corpo e mente fundidos com o de uma ninja.', '1976-12-01'),
(19, 'Stephen Strange', 'Doutor Estranho', 'Magia, manipulação das artes místicas', 'Dependência de feitiços', 'Um cirurgião que se tornou o Feiticeiro Supremo para proteger a Terra de ameaças místicas.', '1963-07-01'),
(20, 'Reed Richards', 'Senhor Fantástico', 'Elasticidade, intelecto avançado', 'Arrogância', 'Líder do Quarteto Fantástico, com a habilidade de esticar seu corpo em formas impossíveis.', '1961-11-01'),
(21, 'Scott Summers', 'Ciclope', 'Rajadas ópticas de energia', 'Incapacidade de controlar os raios sem óculos especiais', 'Líder dos X-Men, emite poderosas rajadas de energia de seus olhos.', '1963-09-01'),
(22, 'Barbara Gordon', 'Batgirl', 'Habilidades de combate, tecnologia avançada', 'Lesão na coluna', 'Filha do Comissário Gordon, inspirada pelo Batman a lutar contra o crime.', '1967-01-01'),
(23, 'Selina Kyle', 'Mulher-Gato', 'Habilidades acrobáticas, mestra ladra', 'Laços emocionais com o Batman', 'Ladra habilidosa e anti-heroína com uma relação complexa com o Batman.', '1940-06-01'),
(24, 'John Stewart', 'Lanterna Verde', 'Poder do anel, projeção de energia', 'Fraqueza contra a cor amarela (nos primeiros anos)', 'Um dos primeiros Lanternas Verdes afro-americanos a proteger o setor 2814.', '1971-12-01'),
(25, 'Kara Zor-El', 'Supergirl', 'Super força, voo, visão de calor', 'Kryptonita', 'Prima de Superman, enviada à Terra para protegê-lo, mas chegou anos depois.', '1959-05-01'),
(26, 'Billy Kaplan', 'Wiccano', 'Magia, manipulação de realidade', 'Insegurança sobre seus poderes', 'Filho de Wanda Maximoff, herdou suas habilidades mágicas e telepáticas.', '2005-04-01'),
(27, 'Marc Spector', 'Cavaleiro da Lua', 'Força aprimorada à noite, habilidades de combate', 'Transtorno dissociativo de identidade', 'Ex-mercenário revivido pelo deus egípcio Khonshu para se tornar o Cavaleiro da Lua.', '1975-08-01'),
(28, 'Dinah Lance', 'Canário Negro', 'Grito supersônico, habilidades de combate', 'Relações pessoais', 'Lutadora de artes marciais e vigilante que usa seu Grito do Canário em batalha.', '1947-12-01'),
(29, 'Jessica Drew', 'Mulher-Aranha', 'Força sobre-humana, veneno bioelétrico', 'Tóxica para outras pessoas devido aos feromônios', 'Recebeu poderes de aranha após ser exposta a uma combinação de radiação e veneno.', '1977-04-01'),
(30, 'Johnny Storm', 'Tocha Humana', 'Pirocinese, voo', 'Aversão à água', 'Membro do Quarteto Fantástico, pode inflamar seu corpo e voar.', '1961-11-01');

SELECT * FROM super_heroi;